	 <?php if ($this->pageCount) : ?>
	<div class="pagination">
	
	 	<?php if (isset($this->previous)) : ?>
		<a href="<?php echo $this->url($this->route) ?>?page=<?php echo $this->previous ?>" title="<?php echo $this->translate('First') ?>"> 
			<i class="material-icons">skip_previous</i>
		</a>
		<?php else : ?>
		<a href="#" title="<?php echo $this->translate('First') ?>"> 
			<i class="material-icons" style="opacity:0.2;">skip_previous</i>
		</a>
		<?php endif ?>
		
		<?php foreach ($this->pagesInRange as $page): ?>
		<a href="<?php echo $this->url($this->route);?>?page=<?php echo $page ?>" title="1 <?php echo $this->translate('page')?>">
			<span<?php echo $page==$this->current?' class="current-page"':'' ?>><?php echo $page ?></span>
		</a>
		<?php endforeach; ?>
		
        <?php if (isset($this->next)): ?>
		<a href="<?php echo $this->url($this->route) ?>?page=<?php echo $this->next ?>" title="<?php echo $this->translate('Last') ?>"> 
			<i class="material-icons">skip_next</i>
		</a>
		<?php else : ?>
		<a href="#" title="<?php echo $this->translate('Last') ?>"> 
			<i class="material-icons" style="opacity:0.2;">skip_next</i>
		</a>
        <?php endif; ?>		
	</div>
	<?php endif; ?>