<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('login'));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'login-form');
?>
				<div class="page-content">
					<?php echo $this->form()->openTag($form) ?>
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="padding:0;">
						<img src="/images/login/<?php echo $logoImage ?>" alt="Extend Tecnologia" />
						<?php echo $this->formElementErrors($form->get('login')) ?>
						<?php if(count($flashMessages)>0) : ?>
						<p class="alert">
							<?php echo implode('<br />', $flashMessages) ?>
						</p>
						<?php else : ?>
						<!-- <p class="message">
							Por favor digite seu login e senha para continuar
						</p> -->
						<?php endif ?>
					</div>
			        <?php if ($this->redirect): ?>
			        <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
			        <?php endif ?>
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<?php
						echo $this->formInput($form->get('login'));
						echo $this->formLabel()->openTag($form->get('login'));
						echo $this->translate($form->get('login')->getLabel());
						echo $this->formLabel()->closeTag($form->get('login'));
						?>
					</div>
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<?php
						echo $this->formInput($form->get('password'));
						echo $this->formLabel()->openTag($form->get('password'));
						echo $this->translate($form->get('password')->getLabel());
						echo $this->formLabel()->closeTag($form->get('password'));
						?>
					</div>
				    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<?php
						echo $this->formLabel()->openTag($form->get('connected'));
						echo $this->formInput($form->get('connected'));
						?>
						<span class="mdl-checkbox__label"><?php echo $this->translate($form->get('connected')->getLabel()); ?></span>
						<?php
						echo $this->formLabel()->closeTag($form->get('connected'));
						?>
					</div>
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="padding-top: 0px;">
						<p>If you forgot password, click <a href="<?php echo $this->url('forgot'); ?>" title="Password Recovery">here</a>.</p>
					</div>
					<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
						<?php 
						echo $this->formButton($form->get('submit'));
						?>
					</div>		  
					<?php echo $this->form()->closeTag() ?>
				</div>
				<script type="text/javascript">
				$(document).ready(function() {
					$('#login').click();
			        $('#button-login').click(function(e) {
			            $('#login-form').submit();
			        });
				});
				</script>
