<?php echo $this->doctype(); ?>

<html>
  <head>
	    <!-- Material Design Lite -->
	    <!-- <script src="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.min.js"></script>
	    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-pink.min.css"> -->
	    <!-- Material Design icon font -->
	    <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> -->
		<meta charset="utf-8">

        <?php echo $this->headTitle('Extend R7 '. $this->translate('Login'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('description', 'Extend R7')
        							->appendName('author', 'Extend Tecnologia')
        							->appendName('robots', 'noindex,nofollow')
        							->appendName('viewport', 'width=device-width; initial-scale=1; maximum-scale=1;')
        							->appendName('apple-mobile-web-app-capable', 'yes')
        							->appendName('apple-mobile-web-app-status-bar-style', 'black-translucent') ?>

        <?php /*echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
        				->headLink(array('rel' => 'apple-touch-icon', 'href' => $this->basePath() . 'images/interface/iOS_icon.png'))*/ ?>

        <?php echo $this->headScript()->appendFile('https://storage.googleapis.com/code.getmdl.io/1.0.5/material.js', 'text/javascript')
        							  ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js', 'text/javascript');
        							  //->appendFile('https://storage.googleapis.com/code.getmdl.io/1.0.5/material.js', 'text/javascript');
        							  //->appendFile($this->basePath() . '/js/jquery.min.js', 'text/javascript')
        							  //->appendFile($this->basePath() . '/js/material.min.js', 'text/javascript'); ?>
        
        <?php echo $this->headLink()->appendStylesheet('https://storage.googleapis.com/code.getmdl.io/1.0.5/material.indigo-pink.min.css')
                        ->appendStylesheet('https://fonts.googleapis.com/icon?family=Material+Icons');
                        //->appendStylesheet($this->basePath() . '/css/users/login.css'); ?>
		
	    <style type="text/css">
			body										{ display:flex!important; align-items:center!important; justify-content:center; }
			.mdl-layout__container						{ margin-left:30px; width:400px; height:495px; position:relative; }
			#button-login								{ top:0; left:237px; }
		</style>
        
	</head>
	<body>
	    <div class="mdl-layout mdl-js-layout">
	    	<main class="mdl-layout__content">
	    		<?php echo $this->content; ?>
	    	</main>
	    </div>
		<?php echo $this->inlineScript() ?>
	</body>
</html>

