<?php
$title = 'New User Group';
$this->headTitle($this->translate($title));

$form = $this->form;
$form->setAttribute('action', $this->url('roles', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php echo $this->formInput($form->get('id')) ?>
	<div class="mdl-grid" style="margin:0 auto; margin-top:20px; max-width:1000px; display:flex!important; align-items:center!important; justify-content:center;">
		<div class="mdl-cell mdl-cell--4-col">
			<h4><?php echo $this->escapeHtml($this->translate($title)) ?></h4>
			<?php echo $this->formInput($form->get('id')) ?>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<?php echo $this->formInput($form->get('name')) ?>
				<?php echo $this->formLabel($form->get('name')) ?>
			</div>
		</div>
		<div class="mdl-cell mdl-cell--4-col" style="margin-top:70px;">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
				<?php echo $this->formSelect($form->get('status')) ?>
				<?php echo $this->formLabel($form->get('status')) ?>
			</div>
		</div>
	</div>
	<div class="mdl-grid" style="margin:0 auto; margin-top:20px; max-width:1000px; display:flex!important; align-items:top; justify-content:center;">
	<?php
	foreach($form->getFieldsets() as $fieldset) :
		if(count($fieldset->getElements())>0) :
	?>
		<div class="mdl-cell mdl-cell--4-col">
			<h5><?php echo $this->translate($fieldset->getName()) ?></h5>
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
			<?php foreach($fieldset->getElements() as $element) : ?>
			<?php 	echo $this->formLabel()->openTag($element) ?>
				<?php echo $this->formInput($element) ?>
				<span class="mdl-checkbox__label"><?php echo $this->translate($element->getLabel()) ?></span>
			<?php 	echo $this->formLabel()->closeTag($element) ?>
			<?php endforeach; ?>
			</div>
		</div>
	<?php
		endif;
	endforeach;
	?>
	</div>
	<div class="mdl-grid" style="margin:0 auto; margin-top:10px; max-width:1000px; display:flex!important; align-items:center!important; justify-content:center;">
		<div class="mdl-cell mdl-cell--8-col">
				<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" id="button-submit" style="float:right;">
				  <?php echo $this->translate('Submit') ?>
				</button>			
		</div>
	</div>
<script type="text/javascript">
$(document).ready(function() {
	$('#button-submit').bind('click', function(e) {
		$('form#role').submit();
	});
	$('input[name=name]').focus();
});
</script>
